### ISSUE TITLE
My doubts when I run HiTE

### ISSUE THREAD

**Issue by chenxuming-0330** [CSU-KangHu/HiTE#13]
Dear Author,

Thank you for developing such an excellent software.I get some problems when I use HiTE to run my project. Would you give me some  help？
I set my order like “nohup python main.py --genome genome.fasta --thread 10 --outdir outdir/ --domain 1 --intact_anno 1 > HiTE.log 2>&1 &”to run  HiTE.
When the program got finished, I found there're no file named " HiTE_intact.sorted.gff3" as the output file for the parameter "--intact_anno 1". What's wrong with this result?
And when I check the HiTE.log,I found error
"cp: cannot stat ‘/storage/chenxuming/HiTE/20century/NeuralTE_all/classified_TE.fa’: No such file or directory
cp: cannot stat ‘/storage/chenxuming/HiTE/20century/TE_merge_tmp.fa.classified’: No such file or directory"
in step3: generate non-redundant library
another error :
Traceback (most recent call last):
  File "/storage/zhangyunqi/HiTE/./module/get_full_length_annotation.py", line 97, in <module>
    classification = TE_classifications[query_name]
KeyError: 'TIR_584'
in step4: get full-length TE annotation
Did those errors above cause  HiTE_intact.sorted.gff3 non-existent？

**Comment by chenxuming-0330** [comment]
and I I mainly study in TIRs.I also want to know which file can show the detail of TIRs ( such as superfamily,start,end,TIR,TSD)

**Comment by CSU-KangHu** [comment]
Hi @chenxuming-0330,

I apologize for the late response. Based on your error message, it seems there might be an issue with the classification module. But I have redownloaded the code and ran it without encountering any errors. Please try setting both the `--genome` and `--outdir` parameters to absolute paths. 

Using `--intact_anno 1` will provide full-length annotation information for all TEs, including TIRs.

Best,
Kang

**Comment by yangruixue-xue** [comment]
Hello, when I run python /opt/HiTE/main.py --genome /opt//HiTE/demo/genome.fa --thread 40 --out_dir /data/work/bug/, I get the following error, what is the reason?
Input file not exist: /tmp/run_hite_main_genome/intact_LTR.fa
cp: cannot stat ‘/tmp/run_hite_main_genome/NeuralTE_LTR/classified_TE.fa’: No such file or directory @CSU-KangHu @chenxuming-0330
