### ISSUE TITLE
judge_LTR_transposons.py KeyError

### ISSUE THREAD

**Issue by hebuzailikaideshihou** [CSU-KangHu/HiTE#15]
When using HiTE, I encountered KeyError using different genomes. Hope to get your answer.

Script：
#!/bin/bash
source ~/anaconda3/bin/activate HiTE
python /work/home/qljgroup02/01.chinese/01.wg/software/HiTE/main.py --genome /work/home/qljgroup02/01.chinese/01.wg/01.waterfolw/Mask_data.new/Pavo_muticus.fa --outdir /work/home/qljgroup02/01.chinese/01.wg/Test/tmp/tmp2 --curated_lib /work/home/qljgroup02/01.chinese/01.wg/Test/tmp/Aves_a.fasta --thread 48 --plant 0 --chunk_size 100

ERRO

2024-08-14 22:38:00,918 - /work/home/qljgroup02/01.chinese/01.wg/software/HiTE/./module/judge_LTR_transposons.py[line:224] - DEBUG: python /work/home/qljgroup02/01.chinese/01.wg/so
ftware/HiTE/./bin/NeuralTE/src/Classifier.py --data /work/home/qljgroup02/01.chinese/01.wg/Test/tmp/tmp2/intact_LTR.fa --use_TSD 0 --model_path /work/home/qljgroup02/01.chinese/01.
wg/software/HiTE/./bin/NeuralTE/models/NeuralTE_model.h5 --outdir /work/home/qljgroup02/01.chinese/01.wg/Test/tmp/tmp2/NeuralTE_LTR --thread 48 --is_wicker 0
Traceback (most recent call last):
  File "/work/home/qljgroup02/01.chinese/01.wg/software/HiTE/./module/judge_LTR_transposons.py", line 261, in <module>
    label = intact_LTR_labels[intact_ltr_name]
KeyError: 'chr_30:43407104..43418381'

**Comment by CSU-KangHu** [comment]
Hi @hebuzailikaideshihou,

The incompatibility with the pandas version has caused the NeuralTE classification to run incorrectly. I have just pushed a new commit that removes NeuralTE's dependency on pandas. Could you please download the latest version of the HiTE code, re-run the demo data, and test if the program now operates smoothly?

Best regards,
Kang

**Comment by hebuzailikaideshihou** [comment]
Hi Kang,

Thank you very much for your reply. I git chone the code again and rebuilt the conda environment. The same problem occurred without using instance data.

2024-08-15 12:13:47,572 - /work/home/qljgroup02/01.chinese/01.wg/software/HiTE/./module/judge_LTR_transposons.py[line:224] - DEBUG: python /work/home/qljgroup02/01.chinese/01.wg/so
ftware/HiTE/./bin/NeuralTE/src/Classifier.py --data /work/home/qljgroup02/01.chinese/01.wg/Test/tmp/tmp2/intact_LTR.fa --use_TSD 0 --model_path /work/home/qljgroup02/01.chinese/01.
wg/software/HiTE/./bin/NeuralTE/models/NeuralTE_model.h5 --outdir /work/home/qljgroup02/01.chinese/01.wg/Test/tmp/tmp2/NeuralTE_LTR --thread 48 --is_wicker 0
Traceback (most recent call last):
  File "/work/home/qljgroup02/01.chinese/01.wg/software/HiTE/./module/judge_LTR_transposons.py", line 261, in <module>
    label = intact_LTR_labels[intact_ltr_name]
KeyError: 'chr_30:43407104..43418381'


Best regards,
Wang

**Comment by CSU-KangHu** [comment]
Please try running the following command directly:

```
python /work/home/qljgroup02/01.chinese/01.wg/software/HiTE/./bin/NeuralTE/src/Classifier.py \  
    --data /work/home/qljgroup02/01.chinese/01.wg/Test/tmp/tmp2/intact_LTR.fa \  
    --use_TSD 0 \  
    --model_path /work/home/qljgroup02/01.chinese/01.wg/software/HiTE/./bin/NeuralTE/models/NeuralTE_model.h5 \  
    --outdir /work/home/qljgroup02/01.chinese/01.wg/Test/tmp/tmp2/NeuralTE_LTR \  
    --thread 48 \  
    --is_wicker 0
```

**Comment by hebuzailikaideshihou** [comment]
/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:585: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  np.object,
Traceback (most recent call last):
  File "/work/home/qljgroup02/01.chinese/01.wg/software/HiTE/./bin/NeuralTE/src/Classifier.py", line 13, in <module>
    from utils.show_util import showToolName, showTestParams
  File "/work/home/qljgroup02/01.chinese/01.wg/software/HiTE/bin/NeuralTE/src/../utils/show_util.py", line 2, in <module>
    from configs import gpu_config
  File "/work/home/qljgroup02/01.chinese/01.wg/software/HiTE/bin/NeuralTE/src/../configs/gpu_config.py", line 9, in <module>
    import tensorflow as tf
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 46, in <module>
    from tensorflow.python import data
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/data/__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/data/experimental/__init__.py", line 97, in <module>
    from tensorflow.python.data.experimental import service
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 353, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 26, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 20, in <module>
    from tensorflow.python.data.util import structure
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py", line 26, in <module>
    from tensorflow.python.data.util import nest
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 40, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/framework/sparse_tensor.py", line 28, in <module>
    from tensorflow.python.framework import constant_op
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 29, in <module>
    from tensorflow.python.eager import execute
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 27, in <module>
    from tensorflow.python.framework import dtypes
  File "/work/home/qljgroup02/anaconda3/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py", line 585, in <module>
    np.object,
  File "/work/home/qljgroup02/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by CSU-KangHu** [comment]
Could you please use `conda list` to check the version of numpy?

**Comment by hebuzailikaideshihou** [comment]
numpy                     1.19.5           py38h8246c76_3    conda-forge

**Comment by CSU-KangHu** [comment]
I'm using the same version of numpy as you, and I'm not encountering any issues on my side. Based on the error output, it seems that the usage of np.object has been deprecated in numpy versions after 1.20. However, since we're both using numpy 1.19.5, theoretically, this issue should not be present.

Could you please provide the full output of `conda list`? This will help us ensure that there are no inconsistencies or unexpected package versions that might be causing the problem.

**Comment by hebuzailikaideshihou** [comment]
[Uploading conda.list.txt…]()

**Comment by hebuzailikaideshihou** [comment]
conda list > conda.list.txt

The Attach file is conda.list.txt.

[Uploading conda.list.txt…]()

**Comment by CSU-KangHu** [comment]
The link you provided is incorrect, and I'm unable to download it.

**Comment by hebuzailikaideshihou** [comment]
(HiTE)  qljgroup02@r03c08n05 16:08:57
 ~/01.chinese/01.wg/Test/tmp (8) 
$ 
cat conda.list.txt
# packages in environment at /work/home/qljgroup02/anaconda3/envs/HiTE:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
absl-py                   0.15.0             pyhd8ed1ab_0    conda-forge
aiohappyeyeballs          2.3.5              pyhd8ed1ab_0    conda-forge
aiohttp                   3.10.3           py38h2019614_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.3.2              h166bdaf_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
bedtools                  2.30.0               h468198e_3    bioconda
biopython                 1.78             py38h7f8727e_0  
blast                     2.16.0               hc155240_2    bioconda
blinker                   1.8.2              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0            py38h17151c0_1    conda-forge
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.32.3               h4bc722e_0    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.4.0              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
cd-hit                    4.8.1               h43eeafb_10    bioconda
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.17.0           py38heb5c249_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
contourpy                 1.1.1            py38h7f3f72f_1    conda-forge
cryptography              39.0.0           py38h1724139_0    conda-forge
cuda-version              11.1                 hdbd7af8_3    conda-forge
cudatoolkit               11.1.1              hb139c0e_13    conda-forge
cudnn                     8.9.7.29             hbc23b4c_3    conda-forge
curl                      7.87.0               h6312ad2_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
drmaa                     0.7.9                   py_1000    conda-forge
entrez-direct             22.4                 he881be0_0    bioconda
et_xmlfile                1.1.0              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h59595ed_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1           py38h2019614_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
frozenlist                1.4.1            py38h01eb140_0    conda-forge
fuzzysearch               0.7.3            py38h17151c0_5    conda-forge
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
gawk                      5.3.0                ha916aea_0    conda-forge
genometools-genometools   1.6.2            py38h5e2dfeb_4    bioconda
gettext                   0.22.5               he02047a_3    conda-forge
gettext-tools             0.22.5               he02047a_3    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
glib                      2.80.2               hf974151_0    conda-forge
glib-tools                2.80.2               hb6ce0ca_0    conda-forge
gmp                       6.3.0                hac33072_2    conda-forge
google-auth               2.33.0             pyhff2d567_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyhd8ed1ab_1    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
grpc-cpp                  1.39.1               h850795e_1    conda-forge
grpcio                    1.39.0           py38hdd6454d_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.18.5               h9f60fe5_3    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      3.1.0           nompi_py38hafa665b_100    conda-forge
harfbuzz                  3.1.1                h83ec7ef_0    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
hmmer                     3.4                  hdbdd923_1    bioconda
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
htslib                    1.17                 h6bc39ce_1    bioconda
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-metadata        8.2.0              pyha770c72_0    conda-forge
java-jdk                  8.0.112                       1    bioconda
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
keras                     2.6.0              pyhd3eb1b0_0  
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5            py38h7f3f72f_1    conda-forge
krb5                      1.20.1               hf9c8cef_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
levenshtein               0.25.1                   pypi_0    pypi
libasprintf               0.22.5               he8f35ee_3    conda-forge
libasprintf-devel         0.22.5               he8f35ee_3    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.87.0               h6312ad2_0    conda-forge
libdeflate                1.21                 h4bc722e_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgettextpo              0.22.5               he02047a_3    conda-forge
libgettextpo-devel        0.22.5               he02047a_3    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libglib                   2.80.2               hf974151_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libidn2                   2.3.7                hd590300_0    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libllvm11                 11.1.0               he0ac6c6_5    conda-forge
libnghttp2                1.51.0               hdcd2b5c_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libpq                     12.15                h37d81fd_1  
libprotobuf               3.16.0               h780b84a_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libtiff                   4.2.0                hf544144_3    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.16                 hd590300_0    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
ltr_retriever             3.0.0                hdfd78af_0    bioconda
mafft                     7.525                h031d066_1    bioconda
markdown                  3.6                pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5            py38h01eb140_0    conda-forge
matplotlib                3.6.2            py38h578d9bd_0    conda-forge
matplotlib-base           3.6.2            py38h945d387_0  
mpfr                      4.2.1                h38ae2d0_2    conda-forge
multidict                 6.0.5            py38h01eb140_0    conda-forge
munkres                   1.0.7                      py_1    bioconda
mysql-common              8.0.32               h14678bc_0    conda-forge
mysql-libs                8.0.32               h54cf53e_0    conda-forge
ncbi-vdb                  3.1.1                h4ac6f70_1    bioconda
nccl                      2.22.3.1             hee583db_1    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
nseg                      1.0.1                h031d066_4    bioconda
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.100                hca3bf56_0    conda-forge
numpy                     1.19.5           py38h8246c76_3    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
olefile                   0.47               pyhd8ed1ab_0    conda-forge
openjdk                   8.0.112          zulu8.19.0.1_3    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openpyxl                  3.1.5            py38h01eb140_0    conda-forge
openssl                   1.1.1w               hd590300_0    conda-forge
opt_einsum                3.3.0              pyhc1e730c_2    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    1.4.4            py38h47df419_0    conda-forge
pango                     1.48.10              h54213e6_2    conda-forge
patsy                     0.5.6              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.43                hcad00b1_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-file-which           1.23                    pl526_0    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-text-soundex         3.05                 pl526_1000    conda-forge
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pillow                    8.2.0            py38ha0e1e83_1    conda-forge
pip                       24.2               pyhd8ed1ab_0    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
pp                        1.6.4.4                    py_0    bioconda
protobuf                  3.16.0           py38h709712a_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyasn1                    0.6.0              pyhd8ed1ab_0    conda-forge
pyasn1-modules            0.4.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyjwt                     2.9.0              pyhd8ed1ab_1    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py38h578d9bd_8    conda-forge
pyqt-impl                 5.12.3           py38h0ffb2e6_8    conda-forge
pyqt5-sip                 4.19.18          py38h709712a_8    conda-forge
pyqtchart                 5.12             py38h7400c14_8    conda-forge
pyqtwebengine             5.12.1           py38h7400c14_8    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.16               h7a1cb2a_2  
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-flatbuffers        1.12               pyhd8ed1ab_1    conda-forge
python-levenshtein        0.25.1                   pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
qt                        5.12.9               h9d6b050_2    conda-forge
rapidfuzz                 3.9.6                    pypi_0    pypi
re2                       2021.09.01           h9c3ff4c_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
recon                     1.08                 h031d066_7    bioconda
repeatmasker              4.1.1           pl5262hdfd78af_2    bioconda
repeatmodeler             2.0.1                   pl526_0    bioconda
repeatscout               1.0.6                hec16e2b_3    bioconda
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
requests-oauthlib         2.0.0              pyhd8ed1ab_0    conda-forge
rmblast                   2.14.0               h4565617_2    bioconda
rpsbproc                  0.5.0                h6a68c12_0    bioconda
rsa                       4.9                pyhd8ed1ab_0    conda-forge
samtools                  1.18                 hd87286a_0    bioconda
scikit-learn              1.2.0            py38h6a678d5_1  
scipy                     1.9.1            py38hea3f02b_0    conda-forge
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
setuptools                72.1.0             pyhd8ed1ab_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.10               hdb0a2a9_1    conda-forge
sqlite                    3.46.0               h6d4b2fc_0    conda-forge
statsmodels               0.13.2           py38h71d37f0_0    conda-forge
tensorboard               2.11.2             pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.6.1            py38h2b5fc30_4    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tensorflow                2.6.0           cuda111py38h48e9d96_2    conda-forge
tensorflow-base           2.6.0           cuda111py38h152c24c_2    conda-forge
tensorflow-estimator      2.6.0           cuda111py38h7a887f1_2    conda-forge
termcolor                 1.1.0              pyhd8ed1ab_3    conda-forge
tesorter                  1.4.6              pyhdfd78af_1    bioconda
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tornado                   6.4.1            py38hfb59056_0    conda-forge
trf                       4.09.1               h031d066_5    bioconda
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
unicodedata2              15.1.0           py38h01eb140_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
werkzeug                  3.0.3              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               ha56f1ee_1    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.12.1           py38h497a2fe_3    conda-forge
xopen                     0.7.3                      py_0    bioconda
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                hb711507_1    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.10               h5eee18b_1  
yarl                      1.9.4            py38h01eb140_0    conda-forge
zipp                      3.20.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstandard                 0.23.0           py38h62bed22_0    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
(HiTE)  qljgroup02@r03c08n05 16:15:2

**Comment by CSU-KangHu** [comment]
Please follow this step to verify the version of numpy:

![image](https://github.com/user-attachments/assets/570419dd-1e04-4c87-b191-83b30c965285)

**Comment by hebuzailikaideshihou** [comment]
Thank you very much for your reply. I checked the numpy version and found that there may be a problem with the numpy version provided by conda. This may be a problem when conda resolves the dependencies of multiple packages.


python
Python 3.8.16 (default, Jan 17 2023, 23:13:24) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> print(np._version_)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/work/home/qljgroup02/.local/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute '_version_'


**I reinstalled numpy using pip install numpy==1.19.5.**
 
Then，I ran the following code：

python /work/home/qljgroup02/01.chinese/01.wg/software/HiTE/./bin/NeuralTE/src/Classifier.py --data /work/home/qljgroup02/01.chinese/01.wg/Test/tmp/tmp/intact_LTR.fa --use_TSD 0 --model_path /work/home/qljgroup02/01.chinese/01.wg/software/HiTE/./bin/NeuralTE/models/NeuralTE_model.h5 --outdir /work/home/qljgroup02/01.chinese/01.wg/Test/tmp/tmp/NeuralTE_LTR --thread 4 --is_wicker 0

ERRO：
Traceback (most recent call last):
  File "/work/home/qljgroup02/01.chinese/01.wg/software/HiTE/./bin/NeuralTE/src/Classifier.py", line 17, in <module>
    from DataProcessor import DataProcessor
  File "/work/home/qljgroup02/01.chinese/01.wg/software/HiTE/bin/NeuralTE/src/DataProcessor.py", line 14, in <module>
    from utils.data_util import read_fasta_v1, generate_TSD_info, generate_domain_info, generate_terminal_info, \
  File "/work/home/qljgroup02/01.chinese/01.wg/software/HiTE/bin/NeuralTE/src/../utils/data_util.py", line 2022, in <module>
    def to_excel_auto_column_weight(df: pd.DataFrame, writer: ExcelWriter, sheet_name="Shee1"):
NameError: name 'pd' is not defined.

Then,  I add import pandas as pd in /work/home/qljgroup02/01.chinese/01.wg/software/HiTE/bin/NeuralTE/src/../utils/data_util.py

Next, I ran the same code:

Traceback (most recent call last):
  File "/work/home/qljgroup02/01.chinese/01.wg/software/HiTE/./bin/NeuralTE/src/Classifier.py", line 17, in <module>
    from DataProcessor import DataProcessor
  File "/work/home/qljgroup02/01.chinese/01.wg/software/HiTE/bin/NeuralTE/src/DataProcessor.py", line 14, in <module>
    from utils.data_util import read_fasta_v1, generate_TSD_info, generate_domain_info, generate_terminal_info, \
  File "/work/home/qljgroup02/01.chinese/01.wg/software/HiTE/bin/NeuralTE/src/../utils/data_util.py", line 11, in <module>
    import pandas as pd
  File "/work/home/qljgroup02/.local/lib/python3.8/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/work/home/qljgroup02/.local/lib/python3.8/site-packages/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/work/home/qljgroup02/.local/lib/python3.8/site-packages/pandas/compat/numpy/__init__.py", line 24, in <module>
    raise ImportError(
ImportError: this version of pandas is incompatible with numpy < 1.20.3
your numpy version is 1.19.5.
Please upgrade numpy to >= 1.20.3 to use this pandas version



Maybe conda's solution to the environment is too bad, I really want to use singularity. However, due to network problems, the image cannot be obtained effectively. Can you provide the SIF image of Singularity in some places such as network disk?

Thank you!
Best regards,
Wang

**Comment by CSU-KangHu** [comment]
I'm sorry for the inconvenience caused earlier due to network issues and other factors, which prevented us from syncing the latest code to the Singularity image. I will release a new version in the future and then sync it to both the Docker and Singularity images. I completely understand your frustration, but in the meantime, I recommend using Conda.

Could you please try running `pip install pandas=1.4.4` to manually set the Pandas version to 1.4.4? Also, please ensure that the lines import pandas as pd and from pandas import ExcelWriter in the file `/work/home/qljgroup02/01.chinese/01.wg/software/HiTE/bin/NeuralTE/src/../utils/data_util.py` are uncommented, then try again.

**Comment by hebuzailikaideshihou** [comment]
Thank you very much for your reply, follow the code you provided: pip install pandas==1.4.4
import pandas as pd
from pandas import ExcelWriter
I successfully ran the program.

Thank you!
Best regards,
Wang
![Uploading 屏幕截图 2024-08-16 152240.png…]()
