### ISSUE TITLE
Is there any statistics results?

### ISSUE THREAD

**Issue by WangZhSi** [CSU-KangHu/HiTE#2]
Hi, thanks for this software. Is there any statistics results, such as percentage of each type of TEs? Total TEs percentage of whole genome?

**Comment by CSU-KangHu** [comment]
Hi @WangZhSi ,

Thank you for your interest in HiTE. You can run HiTE with the parameter `--annotate 1` to generate statistical results. This will output a file named `HiTE.tbl`, which includes the proportions of various types of TEs. 
You can find the explanations of the outputs at [this link](https://github.com/CSU-KangHu/HiTE?tab=readme-ov-file#outputs).

Best,
Kang
