### ISSUE TITLE
Only LTR in TE annotation

### ISSUE THREAD

**Issue by LeoVincenzi** [CSU-KangHu/HiTE#21]
Dear developers, 
I have succed in running HiTE pipeline, but the statistics of the results (HiTE.tbl) reports results for only the LTR repetitions and the simple repeats. The log file does not highlight any error. How could this be possible? 
Could it be a problem of installed software? I installed HiTE with conda.
I leave you here the tbl file:

```
file name: temp.fa
sequences:           361
total length:  435543761 bp  (435120960 bp excl N/X-runs)
GC level:         34.00 %
bases masked:  206281352 bp ( 47.36 %)
==================================================
               number of      length   percentage
               elements*    occupied  of sequence
--------------------------------------------------
Retroelements       121038     86241643 bp   19.80 %
   SINEs:                0            0 bp    0.00 %
   Penelope              0            0 bp    0.00 %
   LINEs:                0            0 bp    0.00 %
    CRE/SLACS            0            0 bp    0.00 %
     L2/CR1/Rex          0            0 bp    0.00 %
     R1/LOA/Jockey       0            0 bp    0.00 %
     R2/R4/NeSL          0            0 bp    0.00 %
     RTE/Bov-B           0            0 bp    0.00 %
     L1/CIN4             0            0 bp    0.00 %
   LTR elements:    121038     86241643 bp   19.80 %
     BEL/Pao             0            0 bp    0.00 %
     Ty1/Copia       24852     16382263 bp    3.76 %
     Gypsy/DIRS1     19484     15509619 bp    3.56 %
       Retroviral        0            0 bp    0.00 %

DNA transposons          0            0 bp    0.00 %
   hobo-Activator        0            0 bp    0.00 %
   Tc1-IS630-Pogo        0            0 bp    0.00 %
   En-Spm                0            0 bp    0.00 %
   MuDR-IS905            0            0 bp    0.00 %
   PiggyBac              0            0 bp    0.00 %
   Tourist/Harbinger     0            0 bp    0.00 %
   Other (Mirage,        0            0 bp    0.00 %
    P-element, Transib)

Rolling-circles          0            0 bp    0.00 %

Unclassified:       244485     49978714 bp   11.48 %

Total interspersed repeats:   136220357 bp   31.28 %


Small RNA:               0            0 bp    0.00 %

Satellites:              0            0 bp    0.00 %
Simple repeats:      91201     67380348 bp   15.47 %
Low complexity:      18498      2680647 bp    0.62 %
==================================================

* most repeats fragmented by insertions or deletions
  have been counted as one element


RepeatMasker version 4.1.1 , default mode

run with rmblastn version 2.14.0+
The query was compared to classified sequences in ".../confident_TE.cons.fa"
```
Thanks

**Comment by CSU-KangHu** [comment]
Hi @LeoVincenzi,

It seems like there are too many unclassified elements. Could you try running the demo data? For example:

```bash
cd ${pathTo}/HiTE && python main.py --genome demo/genome.fa --thread 40 --outdir demo/test/ > output.log 2>&1
```

I need to check the `output.log` file to determine if the program is running correctly.

Best,  
Kang

**Comment by LeoVincenzi** [comment]
Okay, the output log ia ttached.
[output.log](https://github.com/user-attachments/files/17128292/output.log)
Thanks

**Comment by CSU-KangHu** [comment]
The following error appears in the `output.log`:

![1727255785341](https://github.com/user-attachments/assets/2915c8a7-bd93-4e07-a813-3ba5c61d6074)

This is usually related to version issues with `numpy` and `pandas`. Please refer to the first item under "1. Classification Failure" in the following link:  
https://github.com/CSU-KangHu/HiTE/wiki/Issues-with-installation-and-usage

**Comment by LeoVincenzi** [comment]
Okay, those changes in pandas and numpy package fixed the error in output.log.
I will try now to run again HiTE on my genome with --recover to see if this influence the final annotation. 
I will write here updates to close the issue.

**Comment by r-mashoodh** [comment]
hi @CSU-KangHu 

i too cannot get DNA transposons. i'm using the docker container -- is there a way to update the docker? 

many thanks.

**Comment by CSU-KangHu** [comment]
Hi @r-mashoodh,

I apologize, but I currently don’t have the time to update Docker. I recommend installing via Conda, running the demo data, and checking if you encounter the error messages mentioned. You can also follow the measures outlined in the link: https://github.com/CSU-KangHu/HiTE/wiki/Issues-with-installation-and-usage to resolve any issues.

I’ll attempt to update the Docker version once I finish my current work, provided Docker is accessible. Thank you for your understanding!

**Comment by r-mashoodh** [comment]
hi @CSU-KangHu 

I followed the instructions about updating numpy/pandas using a Conda environment. The numpy version was correct but I had to install pandas ...

`
(HiTE) :~/HiTE$ pip install pandas==1.4.4
Collecting pandas==1.4.4
  Downloading pandas-1.4.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil>=2.8.1 in /mnt/beegfs/home5/zoology/rm786/.local/lib/python3.8/site-packages (from pandas==1.4.4) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /mnt/beegfs/home5/zoology/rm786/.local/lib/python3.8/site-packages (from pandas==1.4.4) (2023.3.post1)
Requirement already satisfied: numpy>=1.18.5 in /mnt/beegfs/home5/zoology/rm786/mambaforge/envs/HiTE/lib/python3.8/site-packages (from pandas==1.4.4) (1.19.5)
Requirement already satisfied: six>=1.5 in /mnt/beegfs/home5/zoology/rm786/mambaforge/envs/HiTE/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas==1.4.4) (1.15.0)
Downloading pandas-1.4.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 18.6 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.3
    Uninstalling pandas-2.0.3:
      Successfully uninstalled pandas-2.0.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
goatools 1.3.11 requires rich, which is not installed.
jcvi 1.3.8 requires jinja2, which is not installed.
jcvi 1.3.8 requires more-itertools, which is not installed.
jcvi 1.3.8 requires natsort, which is not installed.
jcvi 1.3.8 requires pybedtools, which is not installed.
jcvi 1.3.8 requires rich, which is not installed.
ortools 9.8.3296 requires pandas>=2.0.0, but you have pandas 1.4.4 which is incompatible.
Successfully installed pandas-1.4.4
`

Do I need to install all of the above as well? thank you.

**Comment by CSU-KangHu** [comment]
You just need to install the correct versions of NumPy and Pandas. You can try running the HiTE [demo](https://github.com/CSU-KangHu/HiTE#demo). If it generates the necessary output files correctly, then your environment is set up properly.

**Comment by r-mashoodh** [comment]
that's exactly what I did. Numpy version was fine. Then I installed pandas and got the conflicts quoted above. I ran HiTE again (now with both numpy and pandas being the right version) and still no DNA tranposons being annotated.

**Comment by CSU-KangHu** [comment]
ould you please follow the steps below to verify the versions of numpy and pandas? Additionally, could you provide the complete console output log?
![image](https://github.com/user-attachments/assets/0a35af63-ca45-4afb-8684-effc4ef30a20)

**Comment by r-mashoodh** [comment]
as I said, when I folllowed those instructions I got that my numpy version was (1.19.5) and the pandas was wrong. I then used pip to install the correct version of pandas and got various conflicts (see above).

So now:

```
conda activate HiTE
(HiTE) python
Python 3.8.16 (default, Jan 17 2023, 23:13:24) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> print(np.__version__)
1.19.5
>>> import pandas as pd
>>> print(pd.__version__)
1.4.4
```

I ran the test data (demo/genome.fa) see output of HiTE.tbl below:

```
less HiTE.tbl 

Retroelements          376        96016 bp    0.58 %
   SINEs:                0            0 bp    0.00 %
   Penelope              0            0 bp    0.00 %
   LINEs:                0            0 bp    0.00 %
    CRE/SLACS            0            0 bp    0.00 %
     L2/CR1/Rex          0            0 bp    0.00 %
     R1/LOA/Jockey       0            0 bp    0.00 %
     R2/R4/NeSL          0            0 bp    0.00 %
     RTE/Bov-B           0            0 bp    0.00 %
     L1/CIN4             0            0 bp    0.00 %
   LTR elements:       376        96016 bp    0.58 %
     BEL/Pao             0            0 bp    0.00 %
     Ty1/Copia          16        10796 bp    0.07 %
     Gypsy/DIRS1         2        11399 bp    0.07 %
       Retroviral        0            0 bp    0.00 %

DNA transposons          0            0 bp    0.00 %
   hobo-Activator        0            0 bp    0.00 %
   Tc1-IS630-Pogo        0            0 bp    0.00 %
   En-Spm                0            0 bp    0.00 %
   MuDR-IS905            0            0 bp    0.00 %
   PiggyBac              0            0 bp    0.00 %
   Tourist/Harbinger     0            0 bp    0.00 %
   Other (Mirage,        0            0 bp    0.00 %
    P-element, Transib)

Rolling-circles          0            0 bp    0.00 %

Unclassified:        12171      2141237 bp   13.00 %

Total interspersed repeats:     2237253 bp   13.59 %


Small RNA:               0            0 bp    0.00 %

Satellites:              0            0 bp    0.00 %
Simple repeats:       4391       348464 bp    2.12 %
Low complexity:       1138        59938 bp    0.36 %
==================================================

* most repeats fragmented by insertions or deletions
  have been counted as one element
                                                      

RepeatMasker version 4.1.1 , default mode
                                        
run with rmblastn version 2.14.0+
The query was compared to classified sequences in ".../confident_TE.cons.fa"
```

[I]([hite.log](https://github.com/user-attachments/files/17355842/hite.log)) have attached the log as well. 

thanks for your help.

**Comment by CSU-KangHu** [comment]
The following error message appeared in the log file you provided:
![image](https://github.com/user-attachments/assets/83d29eb9-f040-423b-8606-c0a357992e20)

Could you try running this command in the HiTE environment and then display the error message if any occurs?

```bash
python /mnt/beegfs/home5/zoology/rm786/HiTE/./bin/NeuralTE/src/Classifier.py --data /mnt/home5/zoology/rm786/HiTE/demo/test/intact_LTR.fa --use_TSD 0 --model_path /mnt/beegfs/home5/zoology/rm786/HiTE/./bin/NeuralTE/models/NeuralTE_model.h5 --outdir /mnt/home5/zoology/rm786/HiTE/demo/test/NeuralTE_LTR --thread 32 --is_wicker 0
```

**Comment by r-mashoodh** [comment]
hi here's the output:

```
Traceback (most recent call last):
  File "/mnt/beegfs/home5/zoology/rm786/HiTE/./bin/NeuralTE/src/Classifier.py", line 13, in <module>
    from utils.show_util import showToolName, showTestParams
  File "/mnt/beegfs/home5/zoology/rm786/HiTE/bin/NeuralTE/src/../utils/show_util.py", line 2, in <module>
    from configs import gpu_config
  File "/mnt/beegfs/home5/zoology/rm786/HiTE/bin/NeuralTE/src/../configs/gpu_config.py", line 9, in <module>
    import tensorflow as tf
  File "/mnt/beegfs/home5/zoology/rm786/mambaforge/envs/HiTE/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/mnt/beegfs/home5/zoology/rm786/mambaforge/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/mnt/beegfs/home5/zoology/rm786/mambaforge/envs/HiTE/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/mnt/beegfs/home5/zoology/rm786/mambaforge/envs/HiTE/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 14, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/mnt/beegfs/home5/zoology/rm786/mambaforge/envs/HiTE/lib/python3.8/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 14, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/mnt/beegfs/home5/zoology/rm786/mambaforge/envs/HiTE/lib/python3.8/site-packages/tensorflow/core/framework/tensor_pb2.py", line 14, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/mnt/beegfs/home5/zoology/rm786/mambaforge/envs/HiTE/lib/python3.8/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 14, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/mnt/beegfs/home5/zoology/rm786/mambaforge/envs/HiTE/lib/python3.8/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/mnt/home5/zoology/rm786/.local/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 553, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

thanks agai.

**Comment by CSU-KangHu** [comment]
Since I cannot reproduce the installation issue on my end, I’m unsure why it occurred. It appears that manual intervention may be needed to resolve these conflicts.

> Input file not exist: /mnt/home5/zoology/rm786/HiTE/demo/test/intact_LTR.fa

This might be due to the program automatically deleting temporary files after execution. I suggest you rerun the demo data and add the `--debug 1` parameter, which will save all temporary files for easier troubleshooting.

**Comment by r-mashoodh** [comment]
@CSU-KangHu thanks for the tip! I have just run it with the debug parameter and I seem to have acquired DNA transposons finally!

i have attached the log with the --debug flag. Do you see any issues?

[hite_debug.log](https://github.com/user-attachments/files/17363390/hite_debug.log)

**Comment by CSU-KangHu** [comment]
Congratulations! I reviewed the log files and didn't find any issues. Enjoy using the program!
