### ISSUE TITLE
Statistical problems with the output file

### ISSUE THREAD

**Issue by RY-Zheng** [CSU-KangHu/HiTE#23]
Dear developers,
I have run HiTE and output multiple files. These include HiTE.out and HiTE.detail.tbl, but I manually checked the number of sequences in HiTE.out and found it was inconsistent with the number recorded in HiTE.detail.tbl, and the number of HiTE.out records was higher. Could you please answer this question? Also, is there a way to convert HiTE.out to annotation files so that I can extract specific sequences, such as all LTR/Gypsy sequences? Or is there a way to extract sequences based on the statistic results of ITE.detail.tbl or ITE.tbl?

$grep -c "LTR/Gypsy" HiTE.out
**1340604**

HiTE.detail.tbl：
Class                  Count        bpMasked    %masked
=====                  =====        ========     =======
DNA                    --           --           --   
    CMC-EnSpm          2396         692283       0.03% 
    Crypton            822          246074       0.01% 
    MULE               93620        19726548     0.74% 
    Merlin             2169         816875       0.03% 
    PIF-Harbinger      95019        20725099     0.77% 
    TcMar              222014       84862829     3.17% 
    hAT                35133        7498474      0.28% 
LINE                   --           --           --   
    L1                 70974        84627363     3.16% 
LTR                    --           --           --   
    Copia              194336       84748164     3.16% 
    ERV                83462        56049195     2.09% 
    **Gypsy              1123194      1771812252   66.17%** 
RC                     --           --           --   
    Helitron           172698       49453545     1.85% 
SINE                   --           --           --   
    tRNA               16209        2247155      0.08% 
Unknown                121537       31955024     1.19% 
                      ---------------------------------
    total interspersed 2233583      2215460880   82.73%

**Comment by CSU-KangHu** [comment]
It might be due to the merging of overlap records in `HiTE.detail.tbl` from `HiTE.out`. You can refer to the details implemented in RepeatMasker’s `buildSummary.pl`.

If you specify `--annotate 1`, it should also generate the` HiTE.gff` file.

**Comment by RY-Zheng** [comment]
> It might be due to the merging of overlap records in `HiTE.detail.tbl` from `HiTE.out`. You can refer to the details implemented in RepeatMasker’s `buildSummary.pl`.
> 
> If you specify `--annotate 1`, it should also generate the` HiTE.gff` file.

I specified '--annotate 1' and also generated 'HiTE.gff' file. But the HiTE.gff file doesn't seem to have a specific classification, such as LTR/Gypsy.  At the same time, the number of TE in theHiTE.gff file and HiTE.out file is consistent, but it is still inconsistent with the number of HiTE.tbl and HiTE.detail.tbl. Is there a filtering mechanism for HiTE.tbl and HiTE.detail.tbl? I want to extract all the sequences of  HiTE.tbl and HiTE.detail.tbl records.
Thank you very much

**Comment by CSU-KangHu** [comment]
You can follow this guide (https://www.biostars.org/p/382150/) to convert the `.out` file to a `.gff` file. In fact, both the `.out` and `.tbl` files are generated by `RepeatMasker`, as invoked by HiTE. Therefore, to understand the specific correspondence between the `.out` and `.tbl` files, you may need to refer to the `RepeatMasker` code.

**Comment by RY-Zheng** [comment]
Ok, thank you. What I want to ask is how to extract the same number of sequences as recorded in HiTE.detail.tbl. 
Just like
HiTE.detail.tbl:
Class                  Count        bpMasked    %masked
=====                  =====        ========     =======
DNA                    --           --           --
    CMC-EnSpm          2396         692283       0.03%
    Crypton            822          246074       0.01%
    MULE               93620        19726548     0.74%
    Merlin             2169         816875       0.03%
    PIF-Harbinger      95019        20725099     0.77%
    TcMar              222014       84862829     3.17%
    hAT                35133        7498474      0.28%
LINE                   --           --           --
    L1                 70974        84627363     3.16%
LTR                    --           --           --
    Copia              194336       84748164     3.16%
    ERV                83462        56049195     2.09%
    Gypsy              1123194      1771812252   66.17%
Here is a record of the number of LTR/Gypsy as 1123194. How can I extract the complete sequence of these numbers?

Thank you

**Comment by CSU-KangHu** [comment]
I'm not sure why the number of records in the `.detail.tbl` file is inconsistent with that in the `.out` file, as this is generated using RepeatMasker's `buildSummary.pl`, as I mentioned.

If you want to extract LTR/Gypsy sequences, you can easily extract the corresponding sequences based on the `.gff` file and calculate metrics like `Count` and `bpMasked` yourself.
