### ISSUE TITLE
TE annotations with no intact_anno parameter.

### ISSUE THREAD

**Issue by sip123a** [CSU-KangHu/HiTE#24]
Statistics output results. I run HiTE using the default parameters, and since I did not add ```--intact_anno 1``` parameter, there are no gff files and tbl files. Is there a script that can output it directly, because running it from scratch is too slow? Thank you very much.

**Comment by CSU-KangHu** [comment]
Hi @sip123a,

You can rerun HiTE by adding the parameters `--recover 1 --intact_anno 1` at the end of the command. The program will automatically skip the steps that have already been completed based on the results in the output directory. In your case, it should only perform the "get full-length TE annotation" step.

Best,
Kang

**Comment by sip123a** [comment]
Thanks for your quick reply,That's great. I successfully got the statistics file and the gff file. The running speed is very fast and does not need to be started from scratch. I'll close the issue.

Thank you.
