### ISSUE TITLE
about --genome parameter

### ISSUE THREAD

**Issue by AiWoZhongHua011002** [CSU-KangHu/HiTE#28]
Hi @CSU-KangHu I want to ask if I test the human genome and it is diploid with two assembly FA files, do I need to put both FA files after the -- genome in my input

**Comment by CSU-KangHu** [comment]
Hi @AiWoZhongHua011002,

Currently, the `--genome` parameter in HiTE supports only a single FA file. However, we will soon be releasing panHiTE (likely in the next few days), which will support multiple genomes. Therefore, I recommend you use panHiTE.

**Comment by AiWoZhongHua011002** [comment]
I saw in the paper that HiTE is targeted at eukaryotes. Have you ever tested it with human genome data

**Comment by CSU-KangHu** [comment]
We have not yet tested the performance of HiTE on the human genome.
