### ISSUE TITLE
Repeat landscape plots

### ISSUE THREAD

**Issue by victor4110** [CSU-KangHu/HiTE#29]
Hi, 

I wonder if it is possible to construct repeat landscape plots from the HiTE output, as with Repeatmasker.

**Comment by CSU-KangHu** [comment]
Hi @victor4110,  

You can use the `--annotate 1` and `--intact_anno 1` parameters to generate the corresponding annotations.

**Comment by victor4110** [comment]
Hi @CSU-KangHu 

Thanks a lot for your answer.

To construct the repeat landscapes I need to calculate the Kimura divergence. To do it, I normally use the alignment file from repeat masker or data that explicitly details mutations (e.g., substitutions, transitions, and transversions) between transposable elements (TEs) and their consensus sequences.

After running HiTE with  `--annotate 1`  and `--intact_anno 1` parameters. I cannot find the alignment file to calculate the Kimura divergence but maybe I am missing something. Could you explain a bit more? 

Thanks

**Comment by CSU-KangHu** [comment]
Hi @victor4110,

We didn’t keep the `.cat.gz` file previously. You can download the latest versions of `module/annotate_genome.py` and `module/clean_lib.py`, replace the old files, and rerun the process. You will obtain the `HiTE.cat.gz` file.

To calculate the Kimura divergence, you can use the following commands:

1. `gzip -d HiTE.cat.gz`
2. `RepeatMasker/util/calcDivergenceFromAlign.pl -s HiTE.div HiTE.cat`

**Comment by victor4110** [comment]
Hi @CSU-KangHu 

After updating `module/annotate_genome.py` and `module/clean_lib.py`, I successfully created the `HiTE.cat.gz`. The landscape plot looks good and the TE annotation is almost 40% better than the one from Repeatmasker (for a non-model organism). 

Thank you so much for your help and for creating such a good tool.
