### ISSUE TITLE
Inquiry HiTE.tblAbout HiTE.gff and HiTE.tbl

### ISSUE THREAD

**Issue by Hanjiangna** [CSU-KangHu/HiTE#30]
Hello,

I have a question regarding the HiTE.gff file. Does it contain annotations exclusively for transposable elements? Also, in the HiTE.tbl file, it states bases masked: 14933219 bp (18.09%). Does this percentage represent the proportion of transposable elements in the genome?

Thank you

**Comment by CSU-KangHu** [comment]
Hi @Hanjiangna,  

Your issue is similar to #31. If you want to exclude simple repeats from the annotation file, you can modify the `RepeatMasker_command` in `HiTE/module/annotate_genome.py` by adding the parameters `-no_is`, `-norna`, and `-nolow`.
