### ISSUE TITLE
suggestions about LTR_retriever -noanno parameter and container use

### ISSUE THREAD

**Issue by tinyfallen** [CSU-KangHu/HiTE#34]
Dear developers,

Thanks for your great works! I have tried HiTE v3.2 for my genome and I have a little suggestion. As the LAI score becoming a general evaluating indicator for new genome assemblies, the LTR_retriever -noanno parameter, which  prevents LAI calculation, may be customized depending on user's needs to avoid rerunning the LTR_retriever pipeline.

Besides, could you please synchronous update the container image for a user-friendly  installation? I have tried installing locally but failed compiling LtrDetector on our outdated system... So I used apptainer instead to implement running version3.2. 

Many thanks!

**Comment by CSU-KangHu** [comment]
Hi @tinyfallen,  

Thank you for your suggestions. The LAI score is a general evaluation metric for new genome assemblies. However, the goal of HiTE is to generate high-quality TE libraries and annotations, and assessing genome assembly quality is beyond its scope.  

Additionally, our pipeline will soon replace LTR_retriever with a newly developed, more advanced LTR detection tool. If you wish to use the LAI metric, you may need to run LTR_retriever separately.  

Regarding the container image, we are currently making significant updates to HiTE, including the implementation of panHiTE. We are conducting extensive testing to ensure its robustness. Once we consider the features stable, we will release a new version of HiTE along with an updated container image.  

Best regards,  
Kang

**Comment by tinyfallen** [comment]
已收到您发送的邮件！

**Comment by tinyfallen** [comment]
That's great! I'm glad to be one of the first users of your software. How long will it take for your test? I may rearrange my analysis schedule.

**Comment by CSU-KangHu** [comment]
HiTE is now relatively stable, but panHiTE is still undergoing testing. Due to recent issues with our HPC platform, the exact completion timeline remains uncertain.

**Comment by tinyfallen** [comment]
Thanks for your reply! I will keep watching your updates~

**Comment by tinyfallen** [comment]
Another concern is that making changes to the user's .bashrc may not be a good idea (python configure.py). Maybe using relative path to invoke those scripts instead is a better choice.
