### ISSUE TITLE
Identify intact elements of a paticular TE type

### ISSUE THREAD

**Issue by MrbrilliantLL** [CSU-KangHu/HiTE#4]
Hi! Thanks for the excellent tools!

How can I get the annotation of specified TE type (e.g. LTR or TIR)? Like the "Divide and conquer" part in EDTA pipeline. Many thanks!

**Comment by CSU-KangHu** [comment]
Hi @MrbrilliantLL ,

Currently, HiTE can only output all types of transposons, with different types of transposons being saved to separate files. For example, LTRs are found in the `confident_ltr_cut.fa.cons` file, TIRs in the `confident_tir.fa` file, and all types of transposons in the `confident_TE.cons.fa` file.

Thank you for your suggestion. We plan to implement a "Divide and conquer" feature similar to EDTA in the next update.

Best ,
Kang

**Comment by MrbrilliantLL** [comment]
Thanks for your timely response! Looking forward to the next version !!!

**Comment by CSU-KangHu** [comment]
Hi @MrbrilliantLL,

I just submitted a new commit. HiTE now supports the `--te_type` parameter to retrieve specific types of TE output, including `ltr`, `tir`, `helitron`, `non-ltr`, and `all`. I hope this is helpful for you. Note: Currently, this feature is only available in the Conda version of HiTE. The Singularity and Docker images will be updated with the next major release.

I will close this issue for now, but feel free to reopen it if you encounter any further problems.

Best regards,  
Kang
