### ISSUE TITLE
Classification and insertion time of transposons

### ISSUE THREAD

**Issue by MrbrilliantLL** [CSU-KangHu/HiTE#7]
Hello, I have two questions about the HiTE output files:

First, it seems that the naming of transposon classification in the **HiTE.tbl** and **HiTE.out** files is inconsistent. Where can I find the correspondence between the two classification methods? 

Second, the HiTE parameters can be set with `--miu`, but I did not find statistical information about transposon insertion time in the output files. 

Looking forward to your response.

**Comment by CSU-KangHu** [comment]
Hi @MrbrilliantLL,

> First, it seems that the naming of transposon classification in the HiTE.tbl and HiTE.out files is inconsistent. Where can I find the correspondence between the two classification methods?

I assume you want to obtain a more detailed genomic proportion for each type of TE. You can follow these steps:

1. Modify the `Taxonomy.pm` file in RepeatMasker. For example, my path is `/home/hukang/miniconda3/envs/HiTE/share/RepeatMasker/Taxonomy.pm`. Comment out line 72 (`use Text::Soundex;`) using `#`.
2. Run `buildSummary.pl` using the absolute path. For example, my command is `/home/hukang/miniconda3/envs/HiTE/share/RepeatMasker/util/buildSummary.pl HiTE.out > HiTE.detail.tbl`.
3. You will get detailed annotation information, including the annotation proportion for each transposon.
![Detailed Annotation](https://github.com/user-attachments/assets/0c319797-79b1-4c3f-a8b0-0a35e4bf5665)

> Second, the HiTE parameters can be set with --miu, but I did not find statistical information about transposon insertion time in the output files.

HiTE currently utilizes LTR_retriever to identify LTR transposons. Therefore, the `--miu` parameter is actually passed to LTR_retriever. You can check the `genome.rename.fa.pass.list` file to find the insertion times corresponding to LTRs.

Best,
Kang

**Comment by MrbrilliantLL** [comment]
Thank you again for your prompt response. Your answer has effectively solved my problem. I will close this issue.
