### ISSUE TITLE
Construction a panTElib

### ISSUE THREAD

**Issue by porkfan** [CSU-KangHu/HiTE#8]
Dear Professor  Hukang,

I am delighted to see that your work has developed a pipeline capable of accurately identifying full-length TEs. I have also been troubled by the overly fragmented TEs annotated by previous software like EDTA2. However, I believe EDTA2 has its advantages, such as their panEDTA pipeline, which allows the construction of a TE library at the pangenome level. This enables the use of a single library to annotate multiple genomes, facilitating comparison and analysis.

I would like to know if it is possible to use the panEDTA pipeline to cluster libraries constructed by HiTE for multiple genomes, thereby generating a panTElib. Perhaps you could consider adding this functionality in future updates? Additionally, I noticed that your article and the peer review comments highlight the high annotation accuracy of your pipeline. However, focusing only on full-length TEs may overlook many non-full-length TEs that are still abundant in the genome. Could I combine your annotation results with the more comprehensive results from EDTA2 to achieve a more complete and accurate annotation?

Thank you again for your work. Best wishes!
yfchen

**Comment by CSU-KangHu** [comment]
Hi yfchen,

Thank you for your interest in HiTE.

> I would like to know if it is possible to use the panEDTA pipeline to cluster libraries constructed by HiTE for multiple genomes, thereby generating a panTElib.  Perhaps you could consider adding this functionality in future updates?

Yes, I believe replacing EDTA with HiTE should easily allow you to create a panHiTE. In fact, panHiTE is already on our to-do list. For now, you can achieve your goal by directly using HiTE in place of EDTA.

> Additionally, I noticed that your article and the peer review comments highlight the high annotation accuracy of your pipeline. However, focusing only on full-length TEs may overlook many non-full-length TEs that are still abundant in the genome.

Theoretically, using a complete full-length TE library allows for the annotation of both full-length and fragmented (non-full-length) TEs in the genome. Since fragmented TEs originate from full-length TEs, they share high homology and can be easily annotated using RepeatMasker.

> Could I combine your annotation results with the more comprehensive results from EDTA2 to achieve a more complete and accurate annotation?

I do not recommend adding unknown TEs into HiTE unless their reliability can be ensured. For a more comprehensive and accurate annotation, I suggest combining the Repbase and HiTE libraries. In our next update, we will add a `--curated_lib` parameter to allow users to input curated libraries.

Best,
Kang

**Comment by porkfan** [comment]
Thank you very much for your prompt and detailed response. I am excited to hear about the upcoming updates and the potential to create a panHiTE. I appreciate your suggestions and will look forward to utilizing the --curated_lib parameter in the next version.

**Comment by CSU-KangHu** [comment]
Hi @porkfan,

I wanted to let you know that we've just added a `--curated_lib` parameter to HiTE, which allows users to input curated libraries. Currently, this functionality is available only in the Conda version of HiTE. The Singularity and Docker images will be updated in the next major release.

Best regards,

Kang

**Comment by CSU-KangHu** [comment]
Hello @porkfan,

I hope this message finds you well. Thank you for your continued support of HiTE. As we plan to develop panHiTE, we aim to address the key challenges users face and would value your insights on this.

Could you please share what specific problems you would like panHiTE to solve or what types of output files you would find most useful? If it's convenient for you, feel free to add me on WeChat (ID: kk1783486160) so we can discuss this in more detail.

Looking forward to your feedback.

Best regards,  
Kang

**Comment by porkfan** [comment]
> Hello @porkfan,
> 
> I hope this message finds you well. Thank you for your continued support of HiTE. As we plan to develop panHiTE, we aim to address the key challenges users face and would value your insights on this.
> 
> Could you please share what specific problems you would like panHiTE to solve or what types of output files you would find most useful? If it's convenient for you, feel free to add me on WeChat (ID: kk1783486160) so we can discuss this in more detail.
> 
> Looking forward to your feedback.
> 
> Best regards, Kang


Of course! I have added you on WeChat, and we can have more in-depth discussions there. I'm really looking forward to your future work.
