### ISSUE TITLE
Comparison of different software results

### ISSUE THREAD

**Issue by jwli-code** [CSU-KangHu/HiTE#9]
The author has made a very good TE identification software.But I still have some questions.The author provides a streamlined process for comparing TE results.(https://github.com/CSU-KangHu/HiTE/wiki/Experiment-reproduction) But this is a one-step process, there is no command like this 
# run BM_HiTE
```
cd HiTE && python module/lib_evaluation.py -g ${genome} \
 --standard_lib ${standard_lib} \
 --test_lib ${test_lib} \
 --work_dir ${out_dir} \
 --coverage_threshold [0.8/0.95/0.99] \
 --cat Total
```
I can compare the previous BM_RM2, BM_EDTA flow quickly.Is it possible to provide a script like BM_HiTE that can compare the results of different software in the way of BM_RM2 and BM_EDTA

**Comment by CSU-KangHu** [comment]
Hi @jwli-code,

You can use the script available at https://github.com/CSU-KangHu/HiTE/blob/master/module/benchmarking.py. To use only BM_RM2, you can set `--BM_RM2 1 --BM_EDTA 0`. Please ensure that you provide the other necessary parameters to ensure the proper execution of the program.

Best,
Kang

**Comment by jwli-code** [comment]
Thanks,If I already have the results for EDTA and RM, how do I pass in two libs that need to be compared, are these two parameters?
```
    parser.add_argument('--lib_module', metavar='lib_module',
                        help='Please enter the directory for library. Use an absolute path.')
    parser.add_argument('--TE_lib', metavar='TE_lib',
```

**Comment by CSU-KangHu** [comment]
Yes, but could you please copy and modify this script? Change `--lib_module` to `--lib_path` and remove the following parts:
![image](https://github.com/user-attachments/assets/02265c68-6b00-4da9-928c-3f55525498fe)

**Comment by jwli-code** [comment]
thank you
